---

- hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: check version of requests
      shell: hostname
      register: requests_version

    - debug: var=requests_version.stdout

    - name: check Files
      shell: ls -ltr /home/abhkm/
      register: requests_files

    - debug: var=requests_files.stdout

    - name: check Files
      shell: cat /home/abhkm/ver.py
      register: requests_cat

    - debug: var=requests_cat.stdout
