---

- hosts: all
  gather_facts: yes

  tasks:
    - name: check version of requests
      shell: hostname
      register: requests_version

    - debug: var=requests_version.stdout

    - name: Download foo.conf
      get_url:
       url: https://bootstrap.pypa.io/get-pip.py
       dest: /tmp/get-pip.py

    - name: install pip3
      sudo: yes
      shell: python3 /tmp/get-pip.py
      register: requests_pip

    - debug: var=requests_pip.stdout
   
