---

- hosts: localhost
  gather_facts: yes
  sudo: yes

  tasks:
    - name: check version of requests
      shell: pip show requests | grep Version | cut -d ' ' -f 2
      ignore_errors: true
      changed_when: false
      register: requests_version

    - debug: var=requests_version.stdout

    - name: Run a script only if file.txt does not exist on the remote node
      copy: src=/x/home/abhkm/ver/verCheck.py
            dest= /home/abhkm/ver.py
            remote_src=no
            mode=preserve
    - name: Run a script using an executable in a system path
      script: /home/abhkm/ver.py
      args:
        executable: python3
