---

- hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: check version of requests
      shell: hostname
      ignore_errors: true
      changed_when: false
      register: requests_version

    - debug: var=requests_version.stdout

    - name: Run a script using an executable in a system path
      script: /home/abhkm/ver.py
      args:
        executable: python3
