---

- hosts: all
  gather_facts: yes

  tasks:
    - name: check version of requests
      shell: hostname

    - name: Download foo.conf
      get_url:
       url: https://bootstrap.pypa.io/get-pip.py
       dest: /tmp/get-pip.py

    - name: install pip3
      sudo: yes
      shell: python3 /tmp/get-pip.py

    - name: Copy file
      remote_src: yes
      copy: src=/x/home/abhkm/ver/ver.yml dest=/home/abhkm/test.py owner=awx group=awx mode=755

    - name: install pip3
      shell: python3 test.py
      register: requests_pip
    
    - debug: var=requests_pip.stdout
   
