---

- hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: check version of requests
      shell: pip show requests | grep Version | cut -d ' ' -f 2
      ignore_errors: true
      changed_when: false
      register: requests_version

    - debug: var=requests_version.stdout

    - name: Run a script only if file.txt does not exist on the remote node
      script: /home/abhkm/ver.py
      args:
        creates: /Users/abhkm/ansible/ver.yml
    - name: Run a script using an executable in a system path
      script: /home/abhkm/ver.py
      args:
        executable: python3
