---

- hosts: all
  gather_facts: yes
  sudo: yes

  tasks:
    - name: check version of requests
      shell: hostname
      register: requests_version

    - debug: var=requests_version.stdout

    - name: check Files
      shell: ls -ltr /home/abhkm/
      register: requests_files

    - debug: var=requests_files.stdout

    - name: install pip3
      shell: apt install python3-pip
      register: requests_pip

    - debug: var=requests_pip.stdout
   
